server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://47.111.26.194:3306/tourby
    username: tourby
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    thymeleaf:
      mode: LEGACYHTML5
      encoding: UTF-8
      prefix: classpath:/static/            # 静态页面所在的路径，一般在resources文件加下创建
      suffix: .html
  # redis配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
#    打印日志
logging:
  level:
    com.cyclingTour: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

